### ISSUE TITLE
not working correctly in 1.19.10

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [openebs/dynamic-localpv-provisioner#57] opened 2021-05-18 22:03 UTC
**Describe the bug:** A clear and concise description of what the bug is.

It can create PVC/PV correctly and create the pvc-xxx folder properly. However, it can't mount it correctly.

**Steps to reproduce the bug:**

I use Rancher 2.5.8 for this. (with 2.9.0 local-pv and 1.4.0 ndm)
It works fine in 1.19.9 but not 1.19.10. 
Both cluster starts from scratch with exactly the same step.

**Anything else we need to know?:**

- OS ubuntu 20.04

**Comment by niladrih** [comment] 2021-06-02 07:40
@Sam-Lin-MillersLab -- I was not able to reproduce your issue. Here are the specifications of the infra:
- Host machines: AWS EC2 (t3.large)
- OS: Ubuntu 20.06 nodes x 2
```console
$ uname -a
Linux ip-172-31-20-82 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Docker: docker-ce v20.10.6
- Rancher: Rancher v2.5.8
- Rancher kubernetes image: RKE v1.19.10-rancher-1-1
- CNI: flannel

Test performed:
Ran busybox pod on both the nodes with LocalPV Hostpath storage (openebs-hostpath storageclass). Pods mounted volume and wrote 5Gi data into a text file.
Test Pod/volume manifest: https://gist.github.com/niladrih/66a0dc0679d6d9b1b17c21e87ef5783f
Observations --
- Pods ran to completion
- No Warnings/Errors in events
- `ls -lh /var/openebs/local/<pv-name>` showed 5.0Gi niladri.txt files

@Sam-Lin-MillersLab Please confirm if you are still facing this issue.

**Comment by niladrih** [comment] 2021-06-16 15:04
Closing this issue.

**Closed as completed by niladrih** 2021-06-16 15:04 UTC
