### ISSUE TITLE
Endpoints object `openebs.io-local` is constantly updated for no apparent reason

### ISSUE THREAD

**Issue by javiku** [openebs/dynamic-localpv-provisioner#149] opened 2022-11-09 12:48 UTC
**Describe the bug:** 

After installation of the provisioner, a Kubernetes Endpoints object called `openebs.io-local` is created.  
Then, that object is constantly updated (every second or so) for no apparent reason, since its content remains the same.

The updates stop if the `openebs-localpv-provisioner` deployment is scaled to 0 instances.

This seems totally unnecessary and may trigger controllers/operators that monitor Endpoints objects for nothing.

**Expected behaviour:**

The Endpoints object `openebs.io-local` should only be updated if its content must be changed.

**Steps to reproduce the bug:**

Install the provisioner and look at the `openebs.io-local` Endpoints object `resourceVersion`.

**Environment details:**
- OpenEBS version: 3.1.0 (also tested with 3.4.0)
- Kubernetes version: 1.21.10
- Cloud provider or hardware configuration: baremetal
- OS: Ubuntu 20.04.3
- kernel: 5.4.0-131-generic

**Comment by niladrih** [comment] 2024-09-12 09:32
The endpoint is used for leader election, it's intended to work this way by design. This is unfortunately not something we can completely control as it's behaviour introduced by https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner, which is a dependency for this project.

Ref: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/CHANGELOG/CHANGELOG-9.0.md#uncategorized-3

**Comment by niladrih** [comment] 2024-09-12 09:33
Closing this issue. Please reopen this if you need more help here @javiku.

**Closed as completed by niladrih** 2024-09-12 09:33 UTC
