### ISSUE TITLE
[Helm] ServiceAccount doesn't respect .Release.Namespace

### ISSUE THREAD

**Issue by renannprado** [openebs/dynamic-localpv-provisioner#207] opened 2024-11-03 21:12 UTC
**Describe the bug:** the service account definition on the Helm template file doesn't respect the `.Release.Namespace`.

**Expected behaviour:** When you deploy the chart with a namespace, this is reflected in the created objects.

**Steps to reproduce the bug:** just try to deploy the helm chart with a namespace and you'll see that the namespace is not present (at least! maybe there's more, I havent' checked) in the first `ServiceAccount`.

Relevant file:  https://github.com/openebs/dynamic-localpv-provisioner/blob/9a3f5e5a13817644ab42e572b83f5bf980b50847/deploy/helm/charts/templates/rbac.yaml#L5

**Comment by niladrih** [comment] 2024-11-28 10:09
The namespace from the chart should reflect on all of the namespaced resources. Could you share the command you've used to install localpv? Also, what version of helm are you using?

**Comment by LKummer** [comment] 2024-12-25 11:42
I can confirm the chart works as intended and the ServiceAccount is created in the namespace specified by `--namespace`.
Checked both the latest release and installing the chart directly from the `develop` branch.

**Comment by niladrih** [comment] 2024-12-25 12:49
I too am unable to reproduce this. Closing this issue, please reopen if you've been able to reproduce this.

**Closed as completed by niladrih** 2024-12-25 12:49 UTC
Labels: could-not-reproduce
