### ISSUE TITLE
failed to provision volume, no node was specified

### ISSUE THREAD

**Issue by Raboo** [openebs/dynamic-localpv-provisioner#186] opened 2024-05-23 00:31 UTC
**Describe the bug:** failed to provision volume, no node was specified

**Expected behaviour:** provision works

**Steps to reproduce the bug:**

Using https://openebs.github.io/openebs (openebs)

Following values:

```yaml
          engines:
            replicated:
              mayastor:
                enabled: false
            local:
              lvm:
                enabled: false
              zfs:
                enabled: false

          localpv-provisioner:
            enabled: true
            analytics:
              enabled: false

          lvm-localpv:
            enabled: false

          mayastor:
            enabled: false

          zfs-localpv:
            enabled: false

          openebs-crds:
            csi:
              volumeSnapshots:
                enabled: false
                keep: false
```

Storage class
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-vm
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local"
provisioner: openebs.io/local
volumeBindingMode: Immediate
reclaimPolicy: Delete
```

pvc
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/createdForDataVolume: d5113330-83f5-491c-acad-feb543242fdd
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.import.endpoint: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    cdi.kubevirt.io/storage.import.source: http
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.preallocation.requested: "false"
    cdi.kubevirt.io/storage.usePopulator: "false"
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
    volume.kubernetes.io/storage-provisioner: openebs.io/local
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    alerts.k8s.io/KubePersistentVolumeFillingUp: disabled
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
  name: vm-ubuntu-datavolume
  namespace: vm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath-vm
  volumeMode: Filesystem
status:
  phase: Pending
```

**The output of the following commands will help us better understand what's going on**:
I get the following error/event:
```
Type: Warning
Reason: ProvisioningFailed
From: openebs.io/local_openebs-localpv-provisioner-6947fc6f65-gct92_6b42f8f6-4f8b-4270-9a8f-afcab507adbc
Message: failed to provision volume with StorageClass "hostpath-vm": configuration error, no node was specified
```
provisioner logs:
```
I0523 00:20:41.062099       1 controller.go:1366] provision "vm/vm-ubuntu-datavolume" class "hostpath-vm": started
W0523 00:20:41.062319       1 controller.go:937] Retrying syncing claim "6accb10c-577c-4c05-9cb0-b9399215ff77" because failures 2 < threshold 15
E0523 00:20:41.062399       1 controller.go:957] error syncing claim "6accb10c-577c-4c05-9cb0-b9399215ff77": failed to provision volume with StorageClass "hostpath-vm": configuration error, no node was specified
```

* `kubectl get pods -n <openebs_namespace> --show-labels`
```
NAME                                           READY   STATUS    RESTARTS        AGE   LABELS
openebs-localpv-provisioner-6947fc6f65-gct92   1/1     Running   1 (2m53s ago)   28m   app=localpv-provisioner,chart=localpv-provisioner-4.0.0,component=localpv-provisioner,heritage=Helm,name=openebs-localpv-provisioner,openebs.io/component-name=openebs-localpv-provisioner,openebs.io/version=4.0.0,pod-template-hash=6947fc6f65,release=openebs
```

**Anything else we need to know?:**
Using [KubeVirt CDI](https://github.com/kubevirt/containerized-data-importer).
And [Virtink](https://github.com/smartxworks/virtink/).

**Environment details:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`): 4.0.0
- Kubernetes version (use `kubectl version`): v1.30.1 / v1.29.4+k0s
- Cloud provider or hardware configuration: Intel Nuc
- OS (e.g: `cat /etc/os-release`): Alpine Linux v3.19
- kernel (e.g: `uname -a`): `Linux nuc-k8s.local 6.6.30-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Mon, 06 May 2024 07:55:42 +0000 x86_64 Linux
`

**Comment by niladrih** [comment] 2024-06-12 13:55
@Raboo the hostpath provisioner needs to use delayed binding (i.e. `volumeBindingMode: WaitForFirstConsumer`). The volume creation begins when you create the application pod. The name of the Node where the Pod has been scheduled needs to determined before the volume creation can begin for that node.

`volumeBindingMode: Immediate` is not supported. This is documented briefly on the [quickstart.md](https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md) file.

**Comment by niladrih** [comment] 2024-06-12 13:57
@Raboo -- closing this issue. Please re-open if the issue is still current.

**Closed as completed by niladrih** 2024-06-12 13:57 UTC
